#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Haruto Yamamoto <s23C1146PP@s.chibakoudai.jp>


import sys
ans = 0

for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
